on:
  schedule: 
    - cron: '0 16 * * *'

name: Extract COVID data

jobs:
  R-CMD-check:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install dependencies
        run: Rscript -e 'install.packages(c("tidyverse", "here", "xts", "rmarkdown", "knitr", "snakecase", "janitor"))'
      - name: Extract daily data
        run: Rscript -e 'source("hopkins_data.R")'
      - name: Update README links
        run: Rscript -e 'rmarkdown::render("README.Rmd")'
      - name: Commit results
        run: |
          git add extracted README.md README.Rmd
          git commit -m 'Re-extract daily data' || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.GH_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
